INSERT INTO marketplace_adminuser VALUES 
('admin','$2a$10$bVPfLcMGz9QSCrBveKEJ3.ienA7PzooQhVVZgOrIttszcuwiD2ws6','admin@telemune.com','2971232654',1,0,1,'NA'),
('anand','$2a$10$bVPfLcMGz9QSCrBveKEJ3.ienA7PzooQhVVZgOrIttszcuwiD2ws6','gulsan@telemune.com','9878987898',2,0,2,'NA'),
('custcare','$2a$10$bVPfLcMGz9QSCrBveKEJ3.ienA7PzooQhVVZgOrIttszcuwiD2ws6','custcare@telemune.com','7896541230',5,0,5,'NA'),
('mak','$2a$10$bVPfLcMGz9QSCrBveKEJ3.ienA7PzooQhVVZgOrIttszcuwiD2ws6','mak12@gmail.com','123456',1,0,1,'NA'),
('Manjeet','$2a$10$bVPfLcMGz9QSCrBveKEJ3.ienA7PzooQhVVZgOrIttszcuwiD2ws6','manjeet1@gmail.com','123456789',4,0,4,'NA'),
('report','$2a$10$bVPfLcMGz9QSCrBveKEJ3.ienA7PzooQhVVZgOrIttszcuwiD2ws6','report@telemune.com','1234567890',3,0,3,'Ripunjay'),
('yogesh','$2a$10$bVPfLcMGz9QSCrBveKEJ3.ienA7PzooQhVVZgOrIttszcuwiD2ws6','yogesh.manrao@telemune.com','123456789',2,0,2,'Abhishek');


INSERT INTO marketplace_roles VALUES 
(1,'Administrator','System Administrator'),
(2,'gulsan','Normal User'),
(3,'report','for reporting purpose'),
(4,'mayank','mayank'),
(5,'custcare','custcare_http_link'),
(6,'mak','User');

INSERT INTO http_links VALUES 
(1,'Marketplace Admin: Manage Packs '),
(2,'Marketplace Admin: Manage Packs Type '),
(3,'Marketplace Admin: Manage Promo Packs '),
(4,'Marketplace Admin: Add Promo Pack '),
(5,'Marketplace Admin: View Promo Pack '),
(6,'Marketplace Admin: Modify Promo Pack '),
(7,'Marketplace Admin: Delete Promo Pack '),
(10,'Marketplace Admin: Add Pack'),
(11,'Marketplace Admin: View Pack'),
(12,'Marketplace Admin: Modify Pack'),
(13,'Marketplace Admin: Delete Pack'),
(14,'Marketplace Admin: view/Modify/Delete Link'),
(15,'Marketplace Admin: Pack Order Management'),
(16,'Marketplace Admin: WhiteBlackList'),
(17,'Marketplace Admin: Delete WhiteBlackList'),
(18,'Marketplace Admin: Add WhiteBlackList'),
(19,'Marketplace Admin: Modify WhiteBlackList'),
(20,' Marketplace Admin: PromoServiceMapping'),
(21,'Marketplace Admin: Add PromoServiceMapping'),
(22,'Marketplace Admin: Delete PromoServiceMapping'),
(23,'Marketplace Admin: Modify PromoServiceMapping'),
(24,'Marketplace Admin: Modify PromoProducMapping'),
(60,'MarketPlace Admin: Reports'),
(61,'MarketPlace Admin: Pack Purchase Report'),
(62,'MarketPlace Admin: Revenue Report'),
(65,'MarketPlace Admin: Alert Based Report'),
(66,'View Low Balance Pack Mapping'),
(67,'Marketplace Admin: View Pack Type '),
(70,'Marketplace Admin: Pack Type Mapping'),
(71,'Marketplace Admin: Add Pack Type'),
(72,'Marketplace Admin: Delete Pack Type'),
(73,'Marketplace Admin: Modify Pack Type'),
(75,'Marketplace Admin: Pack Mapping'),
(76,'Marketplace Admin: View Pack Mapping'),
(77,'MarketPlace Admin: SMS Template'),
(78,'MarketPlace Admin: TTT Validity'),
(79,'MarketPlace Admin: Role Type'),
(80,'MarketPlace Admin: Add Role'),
(81,'MarketPlace Admin: Delete Role'),
(82,'MarketPlace Admin: Modify Role'),
(83,'MarketPlace Admin: View Role'),
(84,'MarketPlace Admin: AddModify Validity'),
(85,'MarketPlace Admin: View Template'),
(86,'MarketPlace Admin: Modify Template'),
(87,'MarketPlace Admin: User Type'),
(88,'MarketPlace Admin: View User'),
(89,'MarketPlace Admin: Add User'),
(90,'MarketPlace Admin: Delete User'),
(91,'MarketPlace Admin: Modify User'),
(92,'MarketPlace Admin: Custcare Report'),
(93,'MarketPlace Admin: Product Purchase Report'),
(94,'MarketPlace Admin: Retention Report'),
(95,'MarketPlace Admin: Total Usage Report'),
(96,'MarketPlace Admin: Tps Report'),
(97,'MarketPlace Admin: CDR Report'),
(98,'MarketPlace Admin: CustCare Chart'),
(99,'MarketPlace Admin: TTT Transaction Detail'),
(100,'MarketPlace Admin: User Transaction Detail'),
(101,'MarketPlace Admin: User Transaction Failure Detail'),
(102,'MarketPlace Admin: Reload Cache'),
(103,'MarketPlace Admin: Service ActionDetail'),
(104,'MarketPlace Admin: Add Service ActionDetail'),
(105,'MarketPlace Admin: Modify ServiceAction Detail'),
(120,'MarketPlace Admin: Pritam Ray');
