DROP TABLE IF EXISTS http_links;
CREATE TABLE http_links (
  LINK_ID int(4) NOT NULL,
  DESCRIPTION varchar(51) NOT NULL,
  PRIMARY KEY (LINK_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

DROP TABLE IF EXISTS marketplace_adminuser;
CREATE TABLE marketplace_adminuser (
  USER_NAME varchar(15) NOT NULL,
  PASSWORD varchar(128) NOT NULL,
  EMAIL varchar(35) DEFAULT NULL,
  MOBILE_NUM varchar(15) DEFAULT NULL,
  ROLE_ID int(3) NOT NULL,
  FIRST_LOGIN int(2) DEFAULT NULL,
  USER_TYPE int(1) NOT NULL DEFAULT 0,
  CREATED_BY varchar(15) NOT NULL DEFAULT 'NA',
  UNIQUE KEY TELE_58 (USER_NAME),
  KEY TELE_127 (ROLE_ID),
  CONSTRAINT FKa0xrsuyg37hhf1942jhi1smua FOREIGN KEY (ROLE_ID) REFERENCES marketplace_roles (ROLE_ID),
  CONSTRAINT TELE_127 FOREIGN KEY (ROLE_ID) REFERENCES marketplace_roles (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS marketplace_roles;
CREATE TABLE marketplace_roles (
  ROLE_ID int(3) NOT NULL,
  ROLE_NAME varchar(15) NOT NULL,
  DESCRIPTION varchar(50) DEFAULT NULL,
  PRIMARY KEY (ROLE_ID),
  UNIQUE KEY CRBT_ROLES_ROLE_NAME (ROLE_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE web_access (
  LINK_ID int(4) NOT NULL,
  ROLE_ID int(3) NOT NULL,
  IS_ALLOWED varchar(1) DEFAULT 'N',
  KEY FKnumq5j8exgf3lu0o775gwsmcf (LINK_ID),
  KEY FKwm9w4hm0v9ey8l243wyv9doj (ROLE_ID),
  CONSTRAINT FKnumq5j8exgf3lu0o775gwsmcf FOREIGN KEY (LINK_ID) REFERENCES http_links (LINK_ID),
  CONSTRAINT FKwm9w4hm0v9ey8l243wyv9doj FOREIGN KEY (ROLE_ID) REFERENCES marketplace_roles(ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 